VehicleVilla/Controllers/LoginController.cs
using log4net;
using log4net.Config;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using VehicleVilla.Models;
using VehicleVilla.Services;

namespace VehicleVilla.Controllers
{
    public class LoginController : Controller
    {
        // Gather UserDAO
        UserDAO repo = new UserDAO();

        // Gather Logger and HttpContextAccessor
        private readonly IHttpContextAccessor context;
        private static readonly ILog _log = LogManager.GetLogger(System.Reflection.MethodBase.GetCurrentMethod().DeclaringType);

        public LoginController(IHttpContextAccessor httpContextAccessor)
        {
            context = httpContextAccessor;
        }

        /// <summary>
        /// Main Login Page
        /// </summary>
        /// <returns></returns>
        public IActionResult Index()
        {
            _log.Info("User Accessed Login Page."); // Logger INFO

            return View();
        }

        /// <summary>
        /// Logs user into account, and validates user is within the database
        /// </summary>
        /// <param name="username"></param>
        /// <param name="password"></param>
        /// <returns></returns>
        public IActionResult ProcessLogin(string username, string password)
        {
            bool verfied = repo.VerifyAccount(username, password);

            if (verfied)
            {
                // Gather Logged User Information
                UserModel user = repo.GetUserByUsername(username);
                context.HttpContext.Session.SetString("username", username);
                context.HttpContext.Session.SetInt32("id", (int) user.Id);
                
                _log.Info("User Login was Successful."); // Logger INFO

                return View("LoginSuccess", user);
            }
            else
            {
                _log.Warn("User Login was Unsuccesssful."); // Logger WARN

                return View("Index");
            }
        }

        /// <summary>
        /// Shows account details, and account edit page
        /// </summary>
        /// <returns></returns>
        public IActionResult DisplayAccount()
        {
            string logged = context.HttpContext.Session.GetString("username");

            if (logged != null)
            {
                UserModel user = repo.GetUserByUsername(logged);

                _log.Info("User Accessed Account Display"); // Logger INFO

                return View("DisplayAccount", user);
            }
            _log.Info("User Not Logged. Sent to Login Request"); // Logger INFO

            return View("../Products/LoginRequest");
        }

        /// <summary>
        /// Edits and updates accoun within the database
        /// </summary>
        /// <param name="user"></param>
        /// <returns></returns>
        public IActionResult ProcessEdit(UserModel user)
        {
            // Gather User from User ID
            user.Id = context.HttpContext.Session.GetInt32("id");
            repo.UpdateAccount(user);

            _log.Info("User Updated Account Information."); // Logger INFO

            return View("DisplayAccount", user);
        }

        /// <summary>
        /// Logs user out of the webpage, and clears context
        /// </summary>
        /// <returns></returns>
        public IActionResult Logout()
        {
            context.HttpContext.Session.Remove("username");
            context.HttpContext.Session.Remove("id");

            _log.Info("User Logged Out Successfully. Cleared Session Variables."); // Logger INFO

            return View("../Home/Index");
        }
    }
}

VehicleVilla/Controllers/ProductsController.cs
using log4net;
using Microsoft.AspNetCore.Mvc;
using VehicleVilla.Models;
using VehicleVilla.Services;

namespace VehicleVilla.Controllers
{
    public class ProductsController : Controller
    {
        // Gather VehicleDAO and UserDAO
        VehicleDAO repo = new VehicleDAO();
        UserDAO userRepo = new UserDAO();

        // Gather Logger and HttpContextAccessor
        private readonly IHttpContextAccessor context;
        private static readonly ILog _log = LogManager.GetLogger(System.Reflection.MethodBase.GetCurrentMethod().DeclaringType);

        public ProductsController(IHttpContextAccessor httpContextAccessor)
        {
            context = httpContextAccessor;
        }

        /// <summary>
        /// Main Products Browse Page
        /// </summary>
        /// <returns></returns>
        public IActionResult Index()
        {
            _log.Info("User Accessed Browse Page."); // Logger INFO
            return View(repo.AllVehicles());
        }

        /// <summary>
        /// Form to Search for Vehicles
        /// </summary>
        /// <returns></returns>
        public IActionResult SearchForm()
        {
            _log.Info("User Accessed Search Page."); // Logger INFO
            return View();
        }

        /// <summary>
        /// Gathers and Lists Search Results
        /// </summary>
        /// <param name="term"></param>
        /// <returns></returns>
        public IActionResult SearchResults(string term)
        {
            _log.Info("User Searched Vehicles."); // Logger INFO

            List<VehicleModel> vehicleList = repo.SearchVehicles(term);
            return View("Index", vehicleList);
        }
        
        /// <summary>
        /// Removes User from the Database
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        public IActionResult DeleteVehicle(int id)
        {
            _log.Info("User Deleted Vehicle by Vehicle ID."); // Logger INFO

            VehicleModel vehicle = repo.GetVehicleById(id);
            repo.DeleteVehicle(vehicle);

            return View("Index", repo.AllVehicles());
        }

        /// <summary>
        /// Edit Vehicle Input Form
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        public IActionResult EditVehicle(int id)
        {
            _log.Info("User Accessed Vehicle Edit Form."); // Logger INFO

            context.HttpContext.Session.SetInt32("editId", (int)id);
            return View(repo.GetVehicleById(id));
        }

        /// <summary>
        /// Updates Vehicle Information within the Database
        /// </summary>
        /// <param name="vehicle"></param>
        /// <returns></returns>
        public IActionResult ProcessEdit(VehicleModel vehicle)
        {
            // Gather Vehicle ID to Update
            int? id = context.HttpContext.Session.GetInt32("editId");

            if (id != null)
            {
                _log.Info("User Edited Vehicle by Vehicle ID."); // Logger INFO
                vehicle.Id = id;
                repo.UpdateVehicle(vehicle);
                return View("Index", repo.AllVehicles());
            }

            _log.Warn("Vehicle Could Not be Updated."); // Logger INFO

            return View("Index", repo.AllVehicles());
        }

        /// <summary>
        /// Create Vehicle Input Form
        /// </summary>
        /// <returns></returns>
        public IActionResult CreateVehicle()
        {
            _log.Info("User Accessed Vehicle Creation Page."); // Logger INFO

            return View("CreateVehicle");
        }

        /// <summary>
        /// Creates a new vehicle in the databse
        /// </summary>
        /// <param name="vehicle"></param>
        /// <returns></returns>
        public IActionResult ProcessCreate(VehicleModel vehicle)
        {
            UserModel user = userRepo.GetUserByUsername(context.HttpContext.Session.GetString("username"));
            vehicle.User = user.Id;

            repo.AddVehicle(vehicle);

            _log.Info("User Created a New Vehicle."); // Logger INFO

            return View("Index", repo.AllVehicles());
        }

        /// <summary>
        /// Shows Vehicle Information base on ID
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        public IActionResult ShowVehicleDetails(int id)
        {
            _log.Info("User Accessed Vehicle Details."); // Logger INFO

            return View(repo.GetVehicleById(id));
        }

        /// <summary>
        /// Displays a List of Vehicles created by logged user
        /// </summary>
        /// <returns></returns>
        public IActionResult MyListings()
        {
            string logged = context.HttpContext.Session.GetString("username");

            if (logged != null)
            {
                List<VehicleModel> myVehicles = new List<VehicleModel>();
                UserModel user = userRepo.GetUserByUsername(logged);

                myVehicles = repo.GetVehiclesByUser(user);

                _log.Info("User Accessed User Listings Page."); // Logger INFO

                return View("MyListings", myVehicles);
            }
            else
            {
                _log.Warn("User Not Logged In! Redirected to Login Page."); // Logger INFO

                return View("LoginRequest");
            }
            
        }
    }
}

VehicleVilla/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - VehicleVilla</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/VehicleVilla.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/lux.css" />
</head>
<body>
    <header>
        @Html.Partial("_navbar.cshtml");
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - VehicleVilla - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

VehicleVilla/Views/Shared/_navbar.cshtml
<nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-dark border-bottom box-shadow mb-3">
    <div class="container-fluid">
        <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">VehicleVilla</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
            <ul class="navbar-nav flex-grow-1">
                <li class="nav-item">
                    <a class="nav-link text-light" asp-area="" asp-controller="Products" asp-action="Index">Vehicles</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link text-light" asp-area="" asp-controller="Products" asp-action="SearchForm">Search</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link text-light" asp-area="" asp-controller="Products" asp-action="MyListings">My Listings</a>
                </li>
            </ul>
            <ul class="navbar-nav">
                <li class="nav-item">
                    <a class="nav-link text-light" asp-area="" asp-controller="Login" asp-action="DisplayAccount">Account</a>
                </li>
            </ul>
        </div>
    </div>
</nav>